name: Build and SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze with SonarQube
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Check out el código
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Para evitar clones superficiales

      # Paso 2: Configura JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'

      # Paso 3: Cache de las dependencias de Maven
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Paso 4: Ejecutar el análisis con SonarQube
      - name: SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Token desde los Secrets de GitHub
          SONAR_HOST_URL: http://localhost:9000  # Asegúrate de que la URL de tu servidor SonarQube sea correcta
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=JuaanDa_Midaxus_83863a29-c3fd-48df-a78d-e43d1667f51a \
            -Dsonar.projectName="Midaxus" \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN
